version: "3.8"

services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_CLEANUP: "true"
      TZ: "UTC"
      # # 0-6 or SUN-SAT: So I want Mo-Fr at 6
      WATCHTOWER_SCHEDULE: "0 0 6 * * 1-5"
      WATCHTOWER_POLL_INTERVAL: 60
      WATCHTOWER_TIMEOUT: 60
    restart: unless-stopped

  caddy:
    image: caddy:2
    container_name: ghost-prod-caddy
    depends_on:
      - ghost
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ghost_caddy_data:/data
      - ghost_caddy_config:/config

  ghost:
    image: ghost:5
    container_name: ghost-prod
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 2368:2368
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: db
      database__connection__user: ghost
      database__connection__password: password
      database__connection__database: ghost_production
      url: https://<domain>
      # mail__transport: "${MAIL_TRANSPORT}"
      # mail__options__host: "${MAIL_HOST}"
      # mail__options__port: "${MAIL_PORT}"
      # mail__options__secureConnection: "${MAIL_SECURE_CONNECTION}"
      # mail__options__auth__user: "${MAIL_USER}"
      # mail__options__auth__pass: "${MAIL_PASSWORD}"
    volumes:
      - ghost_content:/var/lib/ghost/content
      - ./config.production.json:/var/lib/ghost/config.production.json

  db:
    image: mysql:8
    container_name: ghost-prod-mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      # see https://hub.docker.com/_/mysql
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ghost_production
      MYSQL_USER: ghost
      MYSQL_PASSWORD: password
    volumes:
      - mysql_ghost_data:/var/lib/mysql

volumes:
  mysql_ghost_data:
  ghost_content:
  ghost_caddy_data:
  ghost_caddy_config:
